---
gutsy:
  feature_toggles:
    name: FeatureToggles
    base_url: 'http://features.dev'
    versions:
      - name: v1
        schema_path: docs/api/v1/schema.json
      - name: v2016
        schema_path: docs/api/v1/schema.json
